export interface Chapter {
    id: string;
    title: string;
    slug: string; // Ensure this is part of the interface
    courseId: string;
    section: string;
    order: number;
    isPremium: boolean;
    estimatedReadTime: number;
    isCompleted?: boolean;
}

export interface Course {
    id: string;
    title: string;
    slug: string;
    description: string;
    icon: string;
    chapterCount: number;
    chapters: Chapter[];
}

export const courses: Course[] = [
    {
        id: "lld",
        slug: "low-level-design",
        title: "Low Level Design",
        description: "A complete path for LLD interviews: OOP foundations, design principles, UML, patterns, and a curated set of real interview problems.",
        icon: "Code2",
        chapterCount: 15,
        chapters: [
            // I. OOP & Object Modeling (inspired by AlgoMaster OOP section)
            {
                id: "lld-classes-objects",
                slug: "classes-and-objects",
                title: "Classes & Objects",
                courseId: "lld",
                section: "I. OOP Foundations",
                order: 1,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-interfaces",
                slug: "interfaces-and-abstraction",
                title: "Interfaces & Abstraction",
                courseId: "lld",
                section: "I. OOP Foundations",
                order: 2,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-inheritance",
                slug: "inheritance-and-polymorphism",
                title: "Inheritance & Polymorphism",
                courseId: "lld",
                section: "I. OOP Foundations",
                order: 3,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-relationships",
                slug: "encapsulation-and-relationships",
                title: "Encapsulation, Aggregation, Composition & Association",
                courseId: "lld",
                section: "I. OOP Foundations",
                order: 4,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },

            // II. Design Principles (aligned with AlgoMaster Design Principles)
            // II. Design Principles
            {
                id: "lld-dry",
                slug: "dry-principle",
                title: "DRY (Don't Repeat Yourself)",
                courseId: "lld",
                section: "II. Design Principles",
                order: 5,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-kiss",
                slug: "kiss-principle",
                title: "KISS (Keep It Simple, Stupid)",
                courseId: "lld",
                section: "II. Design Principles",
                order: 6,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-yagni",
                slug: "yagni-principle",
                title: "YAGNI & Law of Demeter",
                courseId: "lld",
                section: "II. Design Principles",
                order: 7,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-solid-srp",
                slug: "solid-srp",
                title: "SOLID: Single Responsibility Principle",
                courseId: "lld",
                section: "II. Design Principles",
                order: 8,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-solid-ocp",
                slug: "solid-ocp",
                title: "SOLID: Open/Closed Principle",
                courseId: "lld",
                section: "II. Design Principles",
                order: 9,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-solid-lsp",
                slug: "solid-lsp",
                title: "SOLID: Liskov Substitution Principle",
                courseId: "lld",
                section: "II. Design Principles",
                order: 10,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-solid-isp",
                slug: "solid-isp",
                title: "SOLID: Interface Segregation Principle",
                courseId: "lld",
                section: "II. Design Principles",
                order: 11,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-solid-dip",
                slug: "solid-dip",
                title: "SOLID: Dependency Inversion Principle",
                courseId: "lld",
                section: "II. Design Principles",
                order: 12,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },

            // III. UML & Diagrams (based on AlgoMaster UML list)
            {
                id: "lld-uml-class",
                slug: "uml-class-diagrams",
                title: "UML Class Diagrams for LLD",
                courseId: "lld",
                section: "III. UML & Diagrams",
                order: 13,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-uml-sequence",
                slug: "uml-sequence-diagrams",
                title: "Sequence & Use Case Diagrams",
                courseId: "lld",
                section: "III. UML & Diagrams",
                order: 14,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-uml-activity-state",
                slug: "uml-activity-state",
                title: "Activity & State Machine Diagrams",
                courseId: "lld",
                section: "III. UML & Diagrams",
                order: 15,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },

            // IV. Design Patterns (creational, structural, behavioral from AlgoMaster)
            // IV. Design Patterns - Creational
            {
                id: "lld-dp-singleton",
                slug: "singleton-pattern",
                title: "Singleton Pattern",
                courseId: "lld",
                section: "IV. Design Patterns (Creational)",
                order: 16,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-factory",
                slug: "factory-method-pattern",
                title: "Factory Method Pattern",
                courseId: "lld",
                section: "IV. Design Patterns (Creational)",
                order: 17,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-abstract-factory",
                slug: "abstract-factory-pattern",
                title: "Abstract Factory Pattern",
                courseId: "lld",
                section: "IV. Design Patterns (Creational)",
                order: 18,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-builder",
                slug: "builder-pattern",
                title: "Builder Pattern",
                courseId: "lld",
                section: "IV. Design Patterns (Creational)",
                order: 19,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-prototype",
                slug: "prototype-pattern",
                title: "Prototype Pattern",
                courseId: "lld",
                section: "IV. Design Patterns (Creational)",
                order: 20,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },

            // V. Design Patterns - Structural
            {
                id: "lld-dp-adapter",
                slug: "adapter-pattern",
                title: "Adapter Pattern",
                courseId: "lld",
                section: "V. Design Patterns (Structural)",
                order: 21,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-facade",
                slug: "facade-pattern",
                title: "Facade Pattern",
                courseId: "lld",
                section: "V. Design Patterns (Structural)",
                order: 22,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-decorator",
                slug: "decorator-pattern",
                title: "Decorator Pattern",
                courseId: "lld",
                section: "V. Design Patterns (Structural)",
                order: 23,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-composite",
                slug: "composite-pattern",
                title: "Composite Pattern",
                courseId: "lld",
                section: "V. Design Patterns (Structural)",
                order: 24,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-proxy",
                slug: "proxy-pattern",
                title: "Proxy Pattern",
                courseId: "lld",
                section: "V. Design Patterns (Structural)",
                order: 25,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-bridge",
                slug: "bridge-pattern",
                title: "Bridge Pattern",
                courseId: "lld",
                section: "V. Design Patterns (Structural)",
                order: 26,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-flyweight",
                slug: "flyweight-pattern",
                title: "Flyweight Pattern",
                courseId: "lld",
                section: "V. Design Patterns (Structural)",
                order: 27,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },

            // VI. Design Patterns - Behavioral
            {
                id: "lld-dp-strategy",
                slug: "strategy-pattern",
                title: "Strategy Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 28,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-observer",
                slug: "observer-pattern",
                title: "Observer Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 29,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-command",
                slug: "command-pattern",
                title: "Command Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 30,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-state",
                slug: "state-pattern",
                title: "State Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 31,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-iterator",
                slug: "iterator-pattern",
                title: "Iterator Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 32,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-template",
                slug: "template-method-pattern",
                title: "Template Method Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 33,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-chain",
                slug: "chain-of-responsibility-pattern",
                title: "Chain of Responsibility Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 34,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-mediator",
                slug: "mediator-pattern",
                title: "Mediator Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 35,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-visitor",
                slug: "visitor-pattern",
                title: "Visitor Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 36,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-dp-memento",
                slug: "memento-pattern",
                title: "Memento Pattern",
                courseId: "lld",
                section: "VI. Design Patterns (Behavioral)",
                order: 37,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },

            // V. LLD Interview Framework (inspired by Hello Interview LLD guide & AlgoMaster tips)
            {
                id: "lld-interview-framework",
                slug: "lld-interview-framework",
                title: "Delivery Framework: Problem Analysis, Class Design & Boundaries",
                courseId: "lld",
                section: "VII. Interview Framework",
                order: 38,
                estimatedReadTime: 30,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "lld-interview-tips",
                slug: "lld-interview-tips",
                title: "How to Answer an LLD Interview Question",
                courseId: "lld",
                section: "VII. Interview Framework",
                order: 39,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },

            // VI. LLD Problems – Easy (AlgoMaster Easy list)
            {
                id: "lld-tictactoe",
                slug: "design-tic-tac-toe",
                title: "Design Tic Tac Toe",
                courseId: "lld",
                section: "VIII. LLD Problems – Easy",
                order: 40,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-snake-ladder",
                slug: "design-snake-and-ladder",
                title: "Design Snake and Ladder",
                courseId: "lld",
                section: "VIII. LLD Problems – Easy",
                order: 41,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-lru-cache",
                slug: "design-lru-cache",
                title: "Design LRU Cache",
                courseId: "lld",
                section: "VIII. LLD Problems – Easy",
                order: 42,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-parking-lot",
                slug: "design-parking-lot",
                title: "Design Parking Lot",
                courseId: "lld",
                section: "VIII. LLD Problems – Easy",
                order: 43,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-task-management",
                slug: "design-task-management-system",
                title: "Design Task Management System",
                courseId: "lld",
                section: "VIII. LLD Problems – Easy",
                order: 44,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },

            // VII. LLD Problems – Medium (AlgoMaster Medium list)
            {
                id: "lld-stack-overflow",
                slug: "design-stack-overflow",
                title: "Design Stack Overflow",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 45,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-atm",
                slug: "design-atm",
                title: "Design ATM",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 46,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-logging-framework",
                slug: "design-logging-framework",
                title: "Design Logging Framework",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 47,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-pub-sub",
                slug: "design-pub-sub-system",
                title: "Design Pub/Sub System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 48,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-elevator",
                slug: "design-elevator-system",
                title: "Design Elevator System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 49,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-splitwise",
                slug: "design-splitwise",
                title: "Design Splitwise",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 50,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-vending-machine",
                slug: "design-vending-machine",
                title: "Design Vending Machine",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 51,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-car-rental",
                slug: "design-car-rental-system",
                title: "Design Car Rental System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 52,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-hotel-management",
                slug: "design-hotel-management-system",
                title: "Design Hotel Management System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 53,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-digital-wallet",
                slug: "design-digital-wallet-service",
                title: "Design Digital Wallet Service",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 54,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-airline",
                slug: "design-airline-management-system",
                title: "Design Airline Management System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 55,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-library",
                slug: "design-library-management-system",
                title: "Design Library Management System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 56,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-traffic-signal",
                slug: "design-traffic-signal-system",
                title: "Design Traffic Signal Control System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 57,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-concert-ticket",
                slug: "design-concert-ticket-booking-system",
                title: "Design Concert Ticket Booking System",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 58,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-social-network",
                slug: "design-social-network-service",
                title: "Design Social Network Service (like Facebook)",
                courseId: "lld",
                section: "IX. LLD Problems – Medium",
                order: 59,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },

            // VIII. LLD Problems – Hard (AlgoMaster Hard list)
            {
                id: "lld-spotify",
                slug: "design-spotify",
                title: "Design Spotify / Music Streaming Service",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 60,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-amazon",
                slug: "design-amazon",
                title: "Design Amazon / Online Shopping Service",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 61,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-linkedin",
                slug: "design-linkedin",
                title: "Design LinkedIn",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 62,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-cricinfo-hard",
                slug: "design-cricinfo",
                title: "Design CricInfo",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 63,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-chess",
                slug: "design-chess-game",
                title: "Design Chess Game",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 64,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-coffee-vending",
                slug: "design-coffee-vending-machine",
                title: "Design Coffee Vending Machine",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 65,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-restaurant",
                slug: "design-restaurant-management-system",
                title: "Design Restaurant Management System",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 66,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-stock-exchange",
                slug: "design-online-stock-exchange",
                title: "Design Online Stock Exchange",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 67,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-course-registration",
                slug: "design-course-registration-system",
                title: "Design Course Registration System",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 68,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-movie-ticket",
                slug: "design-movie-ticket-booking-system",
                title: "Design Movie Ticket Booking System",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 69,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-online-auction",
                slug: "design-online-auction-system",
                title: "Design Online Auction System",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 70,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-food-delivery",
                slug: "design-online-food-delivery-service",
                title: "Design Online Food Delivery Service",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 71,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "lld-ride-sharing",
                slug: "design-ride-sharing-service",
                title: "Design Ride-Sharing Service (like Uber)",
                courseId: "lld",
                section: "X. LLD Problems – Hard",
                order: 72,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
        ],
    },
    {
        id: "system-design-fundamentals",
        slug: "system-design-fundamentals",
        title: "System Design Fundamentals",
        description: "Master the architecture of global-scale systems. Deep dives into trade-offs, consistency models, and multi-region resilience.",
        icon: "Globe",
        chapterCount: 20,
        chapters: [
            // Introduction
            {
                id: "sd-intro-what",
                slug: "what-is-system-design",
                title: "What is System Design",
                courseId: "system-design-fundamentals",
                section: "Introduction",
                order: 1,
                estimatedReadTime: 10,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-intro-sde2",
                slug: "top-10-sde2-concepts",
                title: "Top 10 SDE-2 SD concepts",
                courseId: "system-design-fundamentals",
                section: "Introduction",
                order: 2,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-intro-senior",
                slug: "top-10-senior-concepts",
                title: "Top 10 Senior engineer SD concepts",
                courseId: "system-design-fundamentals",
                section: "Introduction",
                order: 3,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-intro-staff",
                slug: "top-10-staff-concepts",
                title: "Top 10 Staff engineer SD concepts",
                courseId: "system-design-fundamentals",
                section: "Introduction",
                order: 4,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-intro-process",
                slug: "system-design-interview-process",
                title: "Process for giving system design interviews",
                courseId: "system-design-fundamentals",
                section: "Introduction",
                order: 5,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },

            // Core Concepts
            {
                id: "sd-core-scalability",
                slug: "scalability",
                title: "Scalability",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 6,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-core-availability",
                slug: "availability",
                title: "Availability",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 7,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-core-reliability",
                slug: "reliability",
                title: "Reliability",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 8,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-core-consistency",
                slug: "consistency-models",
                title: "Consistency Models",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 9,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-core-cap",
                slug: "cap-theorem",
                title: "CAP theorem",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 10,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-core-failures",
                slug: "failures-faults-errors",
                title: "Failures vs Faults vs Errors",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 11,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-core-hashing",
                slug: "consistent-hashing",
                title: "Consistent Hashing",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 12,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-core-latency",
                slug: "latency-vs-throughput",
                title: "Latency vs throughput",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 13,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-core-spof",
                slug: "single-point-of-failure",
                title: "SPOF (Single Point of Failure)",
                courseId: "system-design-fundamentals",
                section: "Core Concepts",
                order: 14,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },

            // Networking Essentials
            {
                id: "sd-net-osi",
                slug: "osi-model",
                title: "OSI Model",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 15,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-net-ip",
                slug: "ip-address",
                title: "IP Address",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 16,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-net-dns",
                slug: "dns",
                title: "DNS",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 17,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-net-proxy",
                slug: "proxies",
                title: "Proxy (Forward & Reverse)",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 18,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-net-http",
                slug: "http-https",
                title: "HTTP/HTTPS",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 19,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-net-tcp",
                slug: "tcp-vs-udp",
                title: "TCP vs UDP",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 20,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-net-sockets",
                slug: "sockets-websockets",
                title: "Sockets and WebSockets",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 21,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-net-lb",
                slug: "load-balancers",
                title: "Load Balancers",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 22,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-net-lb-algo",
                slug: "load-balancing-algorithms",
                title: "LB Algorithms",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 23,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-net-checksum",
                slug: "checksums",
                title: "Checksums",
                courseId: "system-design-fundamentals",
                section: "Networking Essentials",
                order: 24,
                estimatedReadTime: 15,
                isPremium: true,
                isCompleted: false,
            },

            // API Design
            {
                id: "sd-api-styles",
                slug: "api-architecture-styles",
                title: "Architecture Styles",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 25,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-api-types",
                slug: "api-types",
                title: "API Types",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 26,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-api-rest",
                slug: "rest-api",
                title: "REST",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 27,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-api-graphql",
                slug: "graphql",
                title: "GraphQL",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 28,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-api-grpc",
                slug: "grpc",
                title: "gRPC",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 29,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-api-webrtc",
                slug: "webrtc",
                title: "WebRTC",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 30,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-api-sse",
                slug: "server-sent-events",
                title: "SSE (Server-Sent Events)",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 31,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-api-gateway",
                slug: "api-gateways",
                title: "API Gateways",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 32,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-api-rate",
                slug: "rate-limiting",
                title: "Rate Limiting & Algorithms",
                courseId: "system-design-fundamentals",
                section: "API Design",
                order: 33,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },

            // Databases
            {
                id: "sd-db-types",
                slug: "database-types",
                title: "Database Types",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 34,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-db-acid",
                slug: "acid-properties",
                title: "ACID",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 35,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sd-db-postgres",
                slug: "postgres-deep-dive",
                title: "SQL - PostgresQL Deep Dive",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 36,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-mongo",
                slug: "mongodb",
                title: "NoSQL - Mongo",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 37,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-dynamo",
                slug: "dynamodb-deep-dive",
                title: "KV - DynamoDB Deep Dive",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 38,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-cassandra",
                slug: "cassandra-deep-dive",
                title: "NoSQL Column - Cassandra Deep Dive",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 39,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-neo4j",
                slug: "neo4j-graph-db",
                title: "Neo4j - Graph Databases",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 40,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-redis",
                slug: "redis-in-memory",
                title: "Redis - In-Memory Databases",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 41,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-s3",
                slug: "s3-storage",
                title: "S3 - Flat File Storage",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 42,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-bloom",
                slug: "bloom-filters",
                title: "Bloom Filters",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 43,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-quadtree",
                slug: "quad-tree",
                title: "Quad Tree",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 44,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-s stables",
                slug: "sstables",
                title: "SSTables",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 45,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-lsm",
                slug: "lsm-trees",
                title: "LSM Trees",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 46,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sd-db-btree",
                slug: "b-plus-trees",
                title: "B+ Trees",
                courseId: "system-design-fundamentals",
                section: "Databases",
                order: 47,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },

            // Data Modelling
            {
                id: "sd-model-intro",
                slug: "data-modelling-intro",
                title: "Data Modelling Introduction",
                courseId: "system-design-fundamentals",
                section: "Data Modelling",
                order: 48,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },

            // Partitioning
            {
                id: "sd-partition-intro",
                slug: "partitioning",
                title: "Partitioning",
                courseId: "system-design-fundamentals",
                section: "Partitioning",
                order: 49,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },

            // Sharding
            {
                id: "sd-sharding-intro",
                slug: "sharding",
                title: "Sharding",
                courseId: "system-design-fundamentals",
                section: "Sharding",
                order: 50,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },

            // Caching
            {
                id: "sd-caching-intro",
                slug: "caching",
                title: "Caching",
                courseId: "system-design-fundamentals",
                section: "Caching",
                order: 51,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
        ],
    },
    {
        id: "system-design-interviews",
        slug: "system-design-interviews", // Renamed from software-system-design
        title: "System Design: The Senior Path",
        description: "Beyond the basics. Master the design of complex, real-world systems with a focus on Staff-level trade-offs and constraints.",
        icon: "AppWindow",
        chapterCount: 20,
        chapters: [
            // System Utilities
            {
                id: "sdi-rate",
                slug: "design-rate-limiter",
                title: "Design a Rate Limiter",
                courseId: "system-design-interviews",
                section: "System Utilities",
                order: 1,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sdi-kv",
                slug: "design-key-value-store",
                title: "Design a Key-Value Store",
                courseId: "system-design-interviews",
                section: "System Utilities",
                order: 2,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-unique-id",
                slug: "design-unique-id-generator",
                title: "Design a Distributed ID Generator",
                courseId: "system-design-interviews",
                section: "System Utilities",
                order: 3,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-url",
                slug: "design-url-shortener",
                title: "Design a URL Shortener (TinyURL)",
                courseId: "system-design-interviews",
                section: "System Utilities",
                order: 4,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "sdi-crawler",
                slug: "design-web-crawler",
                title: "Design a Web Crawler",
                courseId: "system-design-interviews",
                section: "System Utilities",
                order: 5,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            // Content & Social
            {
                id: "sdi-pastebin",
                slug: "design-pastebin",
                title: "Design Pastebin",
                courseId: "system-design-interviews",
                section: "Content & Social",
                order: 6,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-instagram",
                slug: "design-instagram-feed",
                title: "Design Instagram/Twitter News Feed",
                courseId: "system-design-interviews",
                section: "Content & Social",
                order: 7,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-chat",
                slug: "design-whatsapp",
                title: "Design WhatsApp / Messenger",
                courseId: "system-design-interviews",
                section: "Real-time & Interactions",
                order: 8,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-notification",
                slug: "design-notification-system",
                title: "Design a Notification System",
                courseId: "system-design-interviews",
                section: "Real-time & Interactions",
                order: 9,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            // Media
            {
                id: "sdi-youtube",
                slug: "design-youtube-netflix",
                title: "Design YouTube / Netflix",
                courseId: "system-design-interviews",
                section: "Media & Streaming",
                order: 10,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
            // Location
            {
                id: "sdi-uber",
                slug: "design-uber-lyft",
                title: "Design Uber / Lyft",
                courseId: "system-design-interviews",
                section: "Location Based Services",
                order: 11,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-yelp",
                slug: "design-yelp-proximity",
                title: "Design Yelp / Proximity Service",
                courseId: "system-design-interviews",
                section: "Location Based Services",
                order: 12,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-maps",
                slug: "design-google-maps",
                title: "Design Google Maps",
                courseId: "system-design-interviews",
                section: "Location Based Services",
                order: 13,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            // Other
            {
                id: "sdi-google-drive",
                slug: "design-google-drive",
                title: "Design Google Drive / Dropbox",
                courseId: "system-design-interviews",
                section: "Storage Systems",
                order: 14,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            // Fintech Architecture
            {
                id: "sdi-payment",
                slug: "design-payment-system",
                title: "Design a Payment System",
                courseId: "system-design-interviews",
                section: "Fintech Architecture",
                order: 15,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-wallet",
                slug: "design-digital-wallet",
                title: "Design a Digital Wallet",
                courseId: "system-design-interviews",
                section: "Fintech Architecture",
                order: 16,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-stock",
                slug: "design-stock-exchange",
                title: "Design a Stock Exchange",
                courseId: "system-design-interviews",
                section: "Fintech Architecture",
                order: 17,
                estimatedReadTime: 45,
                isPremium: true,
                isCompleted: false,
            },
            // Real-time Analytics
            {
                id: "sdi-ad-click",
                slug: "design-ad-click-aggregation",
                title: "Design Ad Click Aggregation",
                courseId: "system-design-interviews",
                section: "Real-time Analytics",
                order: 18,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-leaderboard",
                slug: "design-realtime-leaderboard",
                title: "Design Real-time Gaming Leaderboard",
                courseId: "system-design-interviews",
                section: "Real-time Analytics",
                order: 19,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "sdi-metrics",
                slug: "design-metrics-monitoring",
                title: "Design Metrics & Monitoring System",
                courseId: "system-design-interviews",
                section: "Real-time Analytics",
                order: 20,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
        ],
    },
    {
        id: "frontend-system-design",
        slug: "frontend-system-design",
        title: "Frontend System Design",
        description: "Master architectural patterns for large-scale web applications. State management, performance, and widely asked case studies.",
        icon: "LayoutTemplate",
        chapterCount: 10,
        chapters: [
            // Fundamentals
            {
                id: "fe-rendering",
                slug: "rendering-patterns",
                title: "Rendering Patterns (CSR, SSR, ISR)",
                courseId: "frontend-system-design",
                section: "Fundamentals",
                order: 1,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "fe-state",
                slug: "state-management",
                title: "State Management & Scalability",
                courseId: "frontend-system-design",
                section: "Fundamentals",
                order: 2,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "fe-perf",
                slug: "performance-optimization",
                title: "Performance Optimization & Critical Path",
                courseId: "frontend-system-design",
                section: "Fundamentals",
                order: 3,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "fe-networking",
                slug: "networking-caching",
                title: "Networking, Caching & CDNs",
                courseId: "frontend-system-design",
                section: "Fundamentals",
                order: 4,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            // Case Studies
            {
                id: "fe-news-feed",
                slug: "design-news-feed-frontend",
                title: "Design Facebook News Feed (Frontend)",
                courseId: "frontend-system-design",
                section: "Case Studies",
                order: 5,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "fe-gallery",
                slug: "design-photo-gallery",
                title: "Design Photo Gallery / Pinterest",
                courseId: "frontend-system-design",
                section: "Case Studies",
                order: 6,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "fe-docs",
                slug: "design-google-docs",
                title: "Design Google Docs (Collaborative Editor)",
                courseId: "frontend-system-design",
                section: "Case Studies",
                order: 7,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "fe-chat",
                slug: "design-chat-messenger",
                title: "Design Messenger / WhatsApp Web",
                courseId: "frontend-system-design",
                section: "Case Studies",
                order: 8,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "fe-autocomplete",
                slug: "design-autocomplete",
                title: "Design Search Autocomplete",
                courseId: "frontend-system-design",
                section: "Case Studies",
                order: 9,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "fe-checkout",
                slug: "design-ecommerce-checkout",
                title: "Design E-commerce Checkout",
                courseId: "frontend-system-design",
                section: "Case Studies",
                order: 10,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
        ],
    },
    {
        id: "staff-plus",
        slug: "staff-plus-design",
        title: "Staff+ Engineering & Leadership",
        description: "Master the skills required for Staff, Principal, and Distinguished roles. Organizational impact, multiyear project design, and cross-functional leadership.",
        icon: "ShieldCheck",
        chapterCount: 5,
        chapters: [
            {
                id: "staff-impact",
                slug: "organizational-impact",
                title: "Driving Organizational Change & RFCs",
                courseId: "staff-plus",
                section: "Leadership",
                order: 1,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "staff-complexity",
                slug: "tackling-complexity",
                title: "Systemic Complexity & Refactoring at Scale",
                courseId: "staff-plus",
                section: "Architecture",
                order: 2,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "staff-tradeoffs",
                slug: "advanced-tradeoffs",
                title: "Advanced Economic & Technical Trade-offs",
                courseId: "staff-plus",
                section: "Architecture",
                order: 3,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "staff-reliability",
                slug: "designing-for-reliability",
                title: "Reliability Engineering & On-call Culture",
                courseId: "staff-plus",
                section: "Leadership",
                order: 4,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
        ],
    },
    {
        id: "ml-system",
        slug: "ml-system-design",
        title: "ML System Design",
        description: "Master ML system design interview concepts, patterns, and 50+ real-world questions.",
        icon: "Bot",
        chapterCount: 15,
        chapters: [
            // Recommendations
            {
                id: "ml-netflix-ranking",
                slug: "netflix-carousel-ranking",
                title: "Netflix Homepage Carousel Ranking",
                courseId: "ml-system",
                section: "Recommendation Systems",
                order: 1,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ml-tiktok-feed",
                slug: "tiktok-feed-ranking",
                title: "TikTok Video Feed Ranking",
                courseId: "ml-system",
                section: "Recommendation Systems",
                order: 2,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ml-youtube-ads",
                slug: "youtube-ads-personalization",
                title: "YouTube Ads Personalization",
                courseId: "ml-system",
                section: "Recommendation Systems",
                order: 3,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ml-friend-rec",
                slug: "friend-recommendation",
                title: "People You May Know (Friend Rec)",
                courseId: "ml-system",
                section: "Recommendation Systems",
                order: 4,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            // Search & Retrieval
            {
                id: "ml-amazon",
                slug: "amazon-search-ranking",
                title: "Amazon Search Results Ranking",
                courseId: "ml-system",
                section: "Search & Retrieval",
                order: 5,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ml-visual-search",
                slug: "pinterest-visual-search",
                title: "Pinterest Visual Search",
                courseId: "ml-system",
                section: "Search & Retrieval",
                order: 6,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ml-semantic-search",
                slug: "enterprise-semantic-search",
                title: "Enterprise Semantic Search",
                courseId: "ml-system",
                section: "Search & Retrieval",
                order: 7,
                estimatedReadTime: 30,
                isPremium: false,
                isCompleted: false,
            },
            // Prediction & Classification
            {
                id: "ml-uber-eta",
                slug: "uber-eta-prediction",
                title: "Uber ETA Prediction",
                courseId: "ml-system",
                section: "Prediction & Classification",
                order: 8,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ml-harmful",
                slug: "harmful-content-detection",
                title: "Harmful Content Detection",
                courseId: "ml-system",
                section: "Prediction & Classification",
                order: 9,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            // ML Infrastructure (Moved from MLOps overlap)
            {
                id: "ml-feature-store",
                slug: "realtime-feature-store",
                title: "Real-time Feature Store Design",
                courseId: "ml-system",
                section: "ML Infrastructure",
                order: 10,
                estimatedReadTime: 30,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "ml-training-platform",
                slug: "scalable-training-platform",
                title: "Distributed Training Platform",
                courseId: "ml-system",
                section: "ML Infrastructure",
                order: 11,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
        ],
    },
    {
        id: "mlops-production",
        slug: "mlops-production",
        title: "MLOps & LLMOps",
        description: "From research to production. Master CI/CD for ML, Model Monitoring, and LLM Operations.",
        icon: "Cpu",
        chapterCount: 6,
        chapters: [
            // Introduction
            {
                id: "mlops-intro-new",
                slug: "mlops-llmops-intro",
                title: "Introduction",
                courseId: "mlops-production",
                section: "Introduction",
                order: 1,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },

            // ML Platforms and OPs
            {
                id: "mlops-cicd-new",
                slug: "cicd-ml-models",
                title: "CI-CD for ML Models",
                courseId: "mlops-production",
                section: "ML Platforms and OPs",
                order: 2,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "mlops-training",
                slug: "distributed-ml-training",
                title: "Distributed ML Training Platform",
                courseId: "mlops-production",
                section: "ML Platforms and OPs",
                order: 3,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "mlops-feature-store",
                slug: "scalable-feature-store",
                title: "Scalable ML Feature Store",
                courseId: "mlops-production",
                section: "ML Platforms and OPs",
                order: 4,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "mlops-inference",
                slug: "scalable-inference-service",
                title: "Scalable ML Inference Service",
                courseId: "mlops-production",
                section: "ML Platforms and OPs",
                order: 5,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "mlops-observability",
                slug: "scalable-ml-observability",
                title: "Scalable ML Observability",
                courseId: "mlops-production",
                section: "ML Platforms and OPs",
                order: 6,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },

            // LLM Platforms and OPs
            {
                id: "llmops-deployment",
                slug: "llm-deployment-scale",
                title: "Deployment of LLM Models at scale",
                courseId: "mlops-production",
                section: "LLM Platforms and OPs",
                order: 7,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "llmops-inference",
                slug: "llm-inference-service",
                title: "LLM Inference Service",
                courseId: "mlops-production",
                section: "LLM Platforms and OPs",
                order: 8,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "llmops-guardrails",
                slug: "llm-guardrails-service",
                title: "LLM Guardrails Service",
                courseId: "mlops-production",
                section: "LLM Platforms and OPs",
                order: 9,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "llmops-obs",
                slug: "llm-observability-platform",
                title: "LLM Observability Platform",
                courseId: "mlops-production",
                section: "LLM Platforms and OPs",
                order: 10,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "llmops-evals",
                slug: "llm-evals-platform",
                title: "LLM Evals Platform",
                courseId: "mlops-production",
                section: "LLM Platforms and OPs",
                order: 11,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
        ],
    },
    {
        id: "ai-native",
        slug: "ai-native-design",
        title: "AI Native Design",
        description: "Learn to architect applications where AI is the core component. Master RAG, Agents, and LLM ops.",
        icon: "BrainCircuit",
        chapterCount: 18,
        chapters: [
            // Introduction
            {
                id: "ai-native-intro",
                slug: "intro-ai-native-design",
                title: "Introduction to AI Native Design",
                courseId: "ai-native",
                section: "Introduction",
                order: 1,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            // LLM Internals
            {
                id: "llm-history",
                slug: "history-of-llms",
                title: "History: Transformers, Attention, GPT, Claude",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 2,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "llm-types",
                slug: "llm-types",
                title: "LLMs and its types",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 3,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "llm-providers",
                slug: "llm-providers",
                title: "Different LLM Providers",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 4,
                estimatedReadTime: 15,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "llm-frameworks",
                slug: "llm-frameworks",
                title: "Different LLM Abstraction Frameworks",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 5,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "llm-tokenization",
                slug: "tokenization",
                title: "Tokenization",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 6,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "llm-attention",
                slug: "attention-mechanism",
                title: "Attention Mechanism",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 7,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "llm-prompt-caching",
                slug: "prompt-caching",
                title: "Prompt Caching",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 8,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "llm-kv-caching",
                slug: "kv-caching",
                title: "Kv caching",
                courseId: "ai-native",
                section: "LLM Internals",
                order: 9,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            // AI Engineering Core Concepts
            {
                id: "ai-native-transformers",
                slug: "transformers-and-llms",
                title: "Transformers and LLMs",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 2,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "ai-native-router",
                slug: "llm-router",
                title: "LLM Router",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 3,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-vector-db",
                slug: "vector-db",
                title: "Vector DB",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 4,
                estimatedReadTime: 25,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "ai-native-semantic-search",
                slug: "genai-semantic-search",
                title: "Semantic Search",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 5,
                estimatedReadTime: 20,
                isPremium: false,
                isCompleted: false,
            },
            {
                id: "ai-native-rag",
                slug: "scalable-rag",
                title: "RAG",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 6,
                estimatedReadTime: 25,
                isPremium: false, // Free preview
                isCompleted: false,
            },
            {
                id: "ai-native-agents",
                slug: "ai-agent-architecture",
                title: "Agent Design Patterns",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 7,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-memory-short",
                slug: "agent-memory-short-term",
                title: "Agent Memories - Short Term",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 8,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-memory-long",
                slug: "agent-memory-long-term",
                title: "Agent Memories - Long Term",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 9,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-context",
                slug: "context-engineering",
                title: "Context Engineering",
                courseId: "ai-native",
                section: "AI Engineering Core Concepts",
                order: 10,
                estimatedReadTime: 20,
                isPremium: true,
                isCompleted: false,
            },
            // Case Studies
            {
                id: "ai-native-search",
                slug: "ai-search-architecture",
                title: "Case Study: AI Search",
                courseId: "ai-native",
                section: "Case Studies",
                order: 11,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-notion",
                slug: "notion-smart-compose",
                title: "Case Study: Notion Smart Compose",
                courseId: "ai-native",
                section: "Case Studies",
                order: 12,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-whispr",
                slug: "whispr-flow-voice",
                title: "Case Study: Whispr Flow (Voice to Text)",
                courseId: "ai-native",
                section: "Case Studies",
                order: 13,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-semantic",
                slug: "billion-scale-semantic-search",
                title: "Case Study: Billion Scale Semantic Search",
                courseId: "ai-native",
                section: "Case Studies",
                order: 14,
                estimatedReadTime: 35,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-deepgram",
                slug: "deepgram-voice-ai",
                title: "Case Study: Deepgram Voice AI at Scale",
                courseId: "ai-native",
                section: "Case Studies",
                order: 15,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-guardrails",
                slug: "scalable-guardrails",
                title: "Case Study: Scalable Guardrails Service",
                courseId: "ai-native",
                section: "Case Studies",
                order: 16,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-audiobook",
                slug: "audiobook-cover-gen",
                title: "Case Study: Audiobook Cover Art Gen",
                courseId: "ai-native",
                section: "Case Studies",
                order: 17,
                estimatedReadTime: 30,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-linkedin",
                slug: "linkedin-banner-gen",
                title: "Case Study: LinkedIn Banner Gen",
                courseId: "ai-native",
                section: "Case Studies",
                order: 18,
                estimatedReadTime: 25,
                isPremium: true,
                isCompleted: false,
            },
            {
                id: "ai-native-video",
                slug: "text-to-video-scale",
                title: "Case Study: Text to Video at Scale",
                courseId: "ai-native",
                section: "Case Studies",
                order: 19,
                estimatedReadTime: 40,
                isPremium: true,
                isCompleted: false,
            },
        ],
    }
];

// Helper to generate chapters for any skipped courses (fallback)
courses.forEach(course => {
    course.chapterCount = course.chapters.length;
});

export function getCourse(slug: string): Course | undefined {
    return courses.find((c) => c.slug === slug);
}

export function getChapter(courseSlug: string, chapterSlug: string): Chapter | undefined {
    const course = getCourse(courseSlug);
    return course?.chapters.find((ch) => ch.slug === chapterSlug);
}

export function getGroupedChapters(course: Course) {
    return course.chapters.reduce((acc, chapter) => {
        if (!acc[chapter.section]) {
            acc[chapter.section] = [];
        }
        acc[chapter.section].push(chapter);
        return acc;
    }, {} as Record<string, Chapter[]>);
}
